//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Udemy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubMenu
    {
        public int id { get; set; }
        public string submenuname { get; set; }
        public string submenuurl { get; set; }
        public Nullable<int> mainmenuid { get; set; }
    
        public virtual MainMenu MainMenu { get; set; }
    }
}
